### PR TITLE
Add a "dark" theme

### PR DESCRIPTION
**Pull request by phanan**
Love your project so much that I went ahead and created a "dark" theme for it:

image

To activate the theme, just add a `theme="dark"` prop into the component.

### CODE REVIEW

**Comment by egoist** [comment]
Maybe the color of title in `EditorWindow` should be lighter, like `white`?

**Comment by egoist** [comment]
I'm thinking about support more color schemes, like solarized theme, and there're another two fancy windows https://jsx-live.now.sh/ 🙌

**Comment by phanan** [comment]
> Maybe the color of title in EditorWindow should be lighter, like white?

Tried it, but tbh it would require more changes to the current (CSS) code base, as it was created to cater for themes to start with (I think). Maybe you re-structure the CSS a bit?

**Comment by phanan** [comment]
The idea of color schemes is great. I'd imagine a revamp of the code, though.

**Pull request merged**
